# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Duplik8s < Formula
  desc "kubectl plugin to duplicate resources in a Kubernetes cluster."
  homepage "https://github.com/Telemaco019/duplik8s"
  version "0.7.0"

  on_macos do
    on_intel do
      url "https://github.com/Telemaco019/duplik8s/releases/download/v0.7.0/duplik8s_Darwin_x86_64.tar.gz"
      sha256 "6fbdcfaa8958b45a8aa81bb69698a01a5e3700217123045d2e24b5a5fdc23ccb"

      def install
        bin.install "duplik8s"
      end
    end
    on_arm do
      url "https://github.com/Telemaco019/duplik8s/releases/download/v0.7.0/duplik8s_Darwin_arm64.tar.gz"
      sha256 "0c82161f71df90e0e669d0ca8df7126418a9f4b9003f7ed9a0b21cc2b04bca6c"

      def install
        bin.install "duplik8s"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Telemaco019/duplik8s/releases/download/v0.7.0/duplik8s_Linux_x86_64.tar.gz"
        sha256 "e257ebacee2f427b7bd602a8927c715aae1c8e7f0ec8239046923d33022f3c42"

        def install
          bin.install "duplik8s"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/Telemaco019/duplik8s/releases/download/v0.7.0/duplik8s_Linux_arm64.tar.gz"
        sha256 "828e6e89ea2481b3c5673733f7259ef5d5a2fd189a989697eb402d1cff743c6c"

        def install
          bin.install "duplik8s"
        end
      end
    end
  end
end
